Repository profclems/compozify, pull requests merged in 2023-07, with the labels that each got.

#2 Add makefile
  .gitignore
  Makefile
  cmd/compozify/main.go
  go.mod
  go.sum
  pkg/parser/mount_test.go
  pkg/parser/parser_test.go
  pkg/parser/ulimit_test.go
Labels: size/M

#3 add readme
  README.md
Labels: size/M

#4 add github actions
  .gitattributes
  .github/workflows/deploy.yml
  .github/workflows/go.yml
  .github/workflows/lint.yml
  .gitignore
  .golangci.yml
  .goreleaser.yml
  Makefile
  cmd/compozify/main.go
  cmd/gen-docs/main.go
  go.mod
  go.sum
  internal/commands/convert.go
  internal/commands/root.go
  internal/version/version.go
  pkg/parser/parser_test.go
  scripts/changelog
Labels: size/L

#6 api: add new parse api
  api/handler/handler.go
  api/main.go
  api/router/router.go
  go.mod
  go.sum
Labels: size/M

#7 pkg/parser: rename NewParser method to New
  api/handler/handler.go
  api/main.go
  internal/commands/convert.go
  pkg/parser/parser.go
  pkg/parser/parser_test.go
Labels: size/S
